# Controls when the workflow will run
on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: /vinfuncapp/vinfuncapp.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --output publishedVinOutput
    
