# Controls when the workflow will run
on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run a multi-line script
      run: |
        ls
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: vinfuncapp
    - name: Build
      run: dotnet build --no-restore
      working-directory: vinfuncapp
    - name: Publish
      run: dotnet publish --configuration Release --output publishedVinOutput
      working-directory: vinfuncapp
    - name: Create a zip file
      run: |
        ls
        pwd
        zip zippedout.zip publishedVinOutput
      working-directory: vinfuncapp
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artofzipped
        path: zippedout.zip
#     - name: Azure Functions Action
#       uses: Azure/functions-action@v1.4.4
#       with:
#         app-name: vinfuncapp
#         package: zippedoutputano.zip
    
